# Generated by Django 3.1.2 on 2020-10-30 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201030_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 14, 57, 49, 936914, tzinfo=utc)),
        ),
    ]
